flags: {}
packages:
- '.'
extra-deps: [ purescript-0.11.7
            , pipes-http-1.0.5 # repeated from purescript's own 1.0.5: https://github.com/purescript/purescript/blob/6c7f561584af2591b851366d914eafa6398ae3e3/stack.yaml
            ]

# taken from purescript-0.11.7: https://github.com/purescript/purescript/blob/v0.11.7/stack.yaml
resolver: nightly-2017-09-10
